create table if not exists public.hkust_research_profiles (
  user_id uuid primary key default gen_random_uuid(),
  participant_id varchar(64) unique not null,
  age_bracket varchar(255) not null,
  cultural_identity varchar(255) not null,
  hkust_school varchar(255) not null,
  ideological_alignment varchar(255) not null,
  consent_version varchar(64) not null default 'legacy-v1',
  consented_at timestamptz not null default now()
);

create table if not exists public.hkust_consent_records (
  id uuid primary key default gen_random_uuid(),
  participant_id varchar(64) not null references public.hkust_research_profiles(participant_id),
  consent_version varchar(64) not null,
  consented_at timestamptz not null default now(),
  unique (participant_id, consent_version)
);

create table if not exists public.hkust_stream_logs (
  id bigint generated by default as identity primary key,
  participant_id varchar(64) not null references public.hkust_research_profiles(participant_id),
  session_id uuid not null,
  scrolled_at timestamptz not null default now(),
  canonical_url text not null,
  sequence_index integer not null check (sequence_index > 0),
    is_sponsored boolean not null default false,
    constraint hkust_stream_logs_canonical_url_check
      check (
        canonical_url ~ '^https://www\.instagram\.com/reels?/[^/]+/?$'
        and canonical_url !~ '^https://www\.instagram\.com/reels?/audio(/|$)'
      ),
    constraint hkust_stream_logs_canonical_url_length_check
      check (char_length(canonical_url) <= 2048)
);

create or replace function public.purge_hkust_study_data()
returns void
language plpgsql
security definer
set search_path = public
as $$
begin
  delete from public.hkust_stream_logs;
  delete from public.hkust_consent_records;
  delete from public.hkust_research_profiles;
end;
$$;

revoke all on function public.purge_hkust_study_data() from public;
grant execute on function public.purge_hkust_study_data() to postgres, service_role;

select cron.schedule(
  'hkust-study-data-purge',
  '0 3 31 12 *',
  $$select public.purge_hkust_study_data()$$
);

create index if not exists hkust_stream_logs_participant_sequence_idx
  on public.hkust_stream_logs (participant_id, sequence_index);

create unique index if not exists hkust_stream_logs_session_sequence_idx
  on public.hkust_stream_logs (participant_id, session_id, sequence_index);

alter table public.hkust_research_profiles enable row level security;
alter table public.hkust_consent_records enable row level security;
alter table public.hkust_stream_logs enable row level security;

create policy "study clients can register profiles"
  on public.hkust_research_profiles
  for insert
  to public
  with check (true);

create policy "study clients can register consent"
  on public.hkust_consent_records
  for insert
  to public
  with check (true);

create policy "study clients can append stream logs"
  on public.hkust_stream_logs
  for insert
  to public
  with check (true);

-- Profile rows remain inaccessible to study clients; the foreign key still
-- requires every submitted participant_id to exist in the research ledger.
