create table if not exists public.hkust_research_profiles (
  user_id uuid primary key default gen_random_uuid(),
  participant_id varchar(64) unique not null,
  age_bracket varchar(255) not null,
  cultural_identity varchar(255) not null,
  hkust_school varchar(255) not null,
  ideological_alignment varchar(255) not null
);

create table if not exists public.hkust_stream_logs (
  id bigint generated by default as identity primary key,
  participant_id varchar(64) not null references public.hkust_research_profiles(participant_id),
  scrolled_at timestamptz not null default now(),
  canonical_url text not null,
  sequence_index integer not null check (sequence_index > 0),
  is_sponsored boolean not null default false
);

create index if not exists hkust_stream_logs_participant_sequence_idx
  on public.hkust_stream_logs (participant_id, sequence_index);

alter table public.hkust_research_profiles enable row level security;
alter table public.hkust_stream_logs enable row level security;

create policy "study clients can register profiles"
  on public.hkust_research_profiles
  for insert
  to public
  with check (true);

create policy "study clients can append stream logs"
  on public.hkust_stream_logs
  for insert
  to public
  with check (true);

-- Profile rows remain inaccessible to study clients; the foreign key still
-- requires every submitted participant_id to exist in the research ledger.
